requirements.txt

Adds Gunicorn for future Container usage
- [ x ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ x ] I have read the [Contribution Guide] and my PR follows them.
- [ x ] I updated my branch with the master branch.
- [ N/A ] I have added tests that prove my fix is effective or that my feature works
- [ N/A ] I have added necessary documentation about the functionality in the appropriate .md file
- [ N/A ] I have added in line documentation to the code I modified
- Adds a dependency

Updated requirements to include gunicorn

---

README.md
project/__init__.py
project/api/views/items.py
project/api/views/items_statuses.py

Closes #4
- [NA] I have added necessary documentation about the functionality in the appropriate .md file
- [NA] I have added in line documentation to the code I modified

Fix #4: Split endpoints

---

manage.py
project/api/models.py
project/api/views/items_statuses.py
project/tests/test_item_statuses.py
project/tests/test_items.py

Implement PATCH /github/item_statuses endpoint and tests

---

project/api/views/items_statuses.py
project/tests/test_item_statuses.py

Implement DELETE /github/item_statuses

---

project/__init__.py
project/api/models.py
project/api/views/users.py
project/tests/test_items.py
project/tests/test_users.py

Closes #7 
- [x ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x ] I have read the [Contribution Guide] and my PR follows them.
- [x ] I updated my branch with the master branch.
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added in line documentation to the code I modified
- Add the add_user endpoint with the corresponding backend functionality

Creating add_user endpoint

---

plugins/github/README.md

Updated Readme.md

---

scripts/README.md
scripts/run-local-react-client
scripts/setup-local-db
scripts/stop-local-react-client
services/client-react/README.md

- Added some helpful scripts to make it easier to run and test environment

Added helpful scripts for user friendly execution

---

README.md

- Fixes a broken link to the the development branch

Fixed broken link to development branch

---

FIRST_TIMERS.md

- Adds a FIRST_TIMERS.md file containing documentation on how to contribute to the repository
- Contains a list of repositories with open and easy issues

Adding first timers file

---

docker-compose-dev.yml
services/looker/README.md

- Updated the docker-compose-dev to include looker environment vars
-

Add looker environment info to docker compose

---

services/github/Dockerfile
services/github/nginx/Dockerfile
services/looker/project/db_creation/Dockerfile
services/tasks/project/db/Dockerfile
services/users/project/db/Dockerfile

Hello,
The use of COPY is preferred over ADD when additional functionalities of ADD are not being used (like spraying the contents of a tar in a folder).
Ref:https://docs.docker.com/engine/articles/dockerfile_best-practices/#add-or-copy
Thanks.
- 
-

Use COPY instead of ADD in Dockerfile

---

README.md

- Add our Developer Experience Engineer career opportunity to the README #49
-

https://github.com/sendgrid/dx-automator/issues/49

---

scripts/README.md
services/github/project/api/views.py

Fixed issue where call returned would not paginate the results.

Fix GraphQL pagination issue

---

README.md
services/github/project/api/views.py
services/github/project/tests/test_github.py

Get the urls of all the remaining open PRs on a give repo name.

GitHub service get all open prs

---

services/looker/main.py
services/looker/project/api/routes.py

Hello,
I have removed unused modules.
What do you think of it?
Thanks.
- 
-

removed unused python modules

---

README.md
docker-compose-dev.yml
init.sh
services/hacktoberfest/.dockerignore
services/hacktoberfest/.env_sample
services/hacktoberfest/Dockerfile-dev
services/hacktoberfest/entrypoint.sh
services/hacktoberfest/manage.py
services/hacktoberfest/project/__init__.py
services/hacktoberfest/project/api/hacktoberfest.py
services/hacktoberfest/project/api/models.py
services/hacktoberfest/project/api/utils/response.py
services/hacktoberfest/project/config.py
services/hacktoberfest/requirements.txt
services/looker/requirements.txt
services/nginx/flask.conf
services/tasks/requirements.txt
services/users/requirements.txt

Add the hacktoberfest service to help manage Hacktoberfest management.

Hacktoberfest Service

---

README.md
examples/follow_up.py
services/github/project/api/views.py

Added another example that finds all issues that need to be followed up.

Retrieve all open issues that need a follow up response

---

README.md
kill.sh
stop.sh

Added some scripts and documentation on how to properly shut down the system.

Documentation on shutting down containers

---

services/client-react/package-lock.json
services/client-react/package.json

- Adds missing npm modules to package.json and package-lock.json

Added missing npm modules

---

README.md
examples/code_review.py
services/github/project/api/views.py

- Adds the functionality of fetching the number of open PRs needing code reviews across all repos

Add code review PR filter

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Adding code of conduct + contributing readme docs to the development branch

---

.github/PULL_REQUEST_TEMPLATE

- Create CONTRIBUTING.md
- Detail Gitflow Workflow

Detail Gitflow Workflow

---

.gitignore
README.md
docker-compose-dev.yml
scripts/init-task-db
services/github/project/api/views.py
services/tasks/manage.py
services/tasks/project/api/models.py
services/tasks/project/api/tasks.py
services/tasks/requirements.txt
services/users/manage.py

- Adds open issues and PRs to tasks-db
- Updated model to have more information/different nullable values

Populate Tasks DB with all open GitHub Issues and PRs

---

examples/follow_up.py
services/client-react/src/App.jsx
services/client-react/src/index.css
services/tasks/manage.py
services/users/manage.py

- Updated triage page to include open security issues and code review prs
- Updated follow up script to include all open prs and issues

Triage and follow up script update

---

services/nginx/flask.conf
services/tasks/project/__init__.py
services/tasks/project/api/routes.py
services/tasks/project/api/tasks.py
services/tasks/project/config.py

As I fixed the tasks service connection, I discovered a timeout issue as well. This PR fixes both of those things.

Fix tasks service for new GitHub service interface 

---

README.md
examples/rice_sorted_list_of_issues_and_prs.py
examples/update_rice_scores.py
services/github/project/api/routes.py
services/tasks/project/api/routes.py
services/tasks/project/tests/test_tasks.py

This PR allows you to retrieve a RICE sorted list of all open issues and PRs in the specified repos.

Get a list of RICE sorted issues and PRs

---

README.md

Update on-boarding copy

---

.gitignore
README.md
examples/README.md
examples/closed_issues.py
examples/closed_prs.py
examples/code_review.py
examples/follow_up.py
examples/hacktoberfest_example.py
examples/open_bugs.py
examples/open_security_issues.py
examples/opened_issues.py
examples/opened_prs.py
examples/releases.py
examples/repos.py
examples/unlabeled_issues.py
services/github/project/api/graphql.py
services/github/project/api/routes.py

* New endpoint for obtaining release data
* New examples for reporting open/closed issues/PRs
* Refactored examples so that the repos are only defined once
* Fixed a bug in the GraphQL module that was causing a syntax error

Reporting updates and bug fix for syntax error

---

CONTRIBUTING.md
README.md
services/github/project/api/routes.py
services/tasks/project/api/routes.py
services/tasks/project/config.py

To test (Python 3):
```bash
./scripts/init-task-db 
python examples/update_rice_scores.py
python examples/rice_sorted_list_of_issues_and_prs.py
```

Twilio GitHub repos now included in RICE scoring

---

services/nginx/flask.conf

This service sometimes will timeout after a successful API call to GitHub.

chore: give more time to the github-service

---

examples/action_items.py
examples/common/issue.py

This only applies to the action items script right now. Aging bugs and enhancements will be sorted so the top thumbs-upped issue summaries will bubble to the top of the list.

feat: sort aging bugs/enhancements by thumbs-up reactions

---

CONTRIBUTING.md
services/github/project/tests/test_github.py

chore: update GitHub branch references to use HEAD

---

examples/action_items.py

The action items now reports on _all_ items, sorted by creation date descending, and limits each category to the first 10 items.

feat: remove action items query date window

---

examples/common/repos.py

- add twilio-go to dx automator
Jira ticket: https://issues.corp.twilio.com/browse/DI-1141

chore: add twilio-go

---

examples/common/repos.py

Jira: https://issues.corp.twilio.com/browse/DI-1141

chore: add twilio-oai-generator

---

examples/common/admins.py

Add Sindhura, Anuj, and Ravali as admins in DX-automator.

chore: add more admins

---

examples/common/admins.py

Update admins in dx-automator.

chore: update admins

---

actions/release/ReleaseGitHub.ts
actions/release/dist/index.js

Fixes https://github.com/sendgrid/sendgrid-php/issues/1082

fix: proper binary upload of assets

---

examples/metrics.py

Internal [Reference1](https://issues.corp.twilio.com/browse/DI-1657) and [Reference2](https://issues.corp.twilio.com/browse/DI-1658)

feat: Adding datadog metrics to collect time to contact for issues and PRs

---

examples/metrics.py

Internal Reference/ Jira ticket: [DI-1659](https://issues.corp.twilio.com/browse/DI-1659)

feat: add time to resolve metric to Datadog

---

examples/common/admins.py

Add Shamant's new username to list of admins.

chore: update admins with Shamant's new username

---

examples/common/admins.py

Add Claudia username to list of admins.

chore: update admin with Claudia username

---

.eslintrc.yml
actions/datadog-release-metric/DatadogReleaseMetric.test.ts
actions/datadog-release-metric/DatadogReleaseMetric.ts

[DI-2043](https://issues.corp.twilio.com/browse/DI-2043)

feat: Updating release metric action to signal release complete

---

examples/common/admins.py

chore: add Matt as admin

---

examples/metrics.py

To calculate aggregate means for a metric, we need counts and sums. Also removes obsolete backfill code.

[DI-2176] fix: send counts and sums instead of mean to Datadog

---

actions/release/dist/index.js
examples/sonar_cloud_metrics.py
tests/test_sonar_cloud_metrics.py

This is so we start adding this tag to metrics sooner and collect more data versus waiting for DI-2253 to be completed.

chore: mark current SonarCloud repo metrics as not being pre-releases

---

examples/common/admins.py

chore: Update admin to include the usernames 

---

examples/metrics.py

Fix so that stale items still get included in these metrics. Also some refactor to simplify.

fix: don't ignore items that are stale for time_open and issue_count metrics

---

examples/metrics.py
terraform/datadog_monitors.tf
tests/test_metrics.py

Also refactors the metrics to use tags for categories instead of suffixes.
Datadog series data for twilio-node:
```json
[{'metric': 'library.issue_count.count',
'points': [[1663348587.680195, 1.0]],
'tags': ['org:twilio',
'repo:twilio/twilio-node',
'category:None',
'type:helper'],
'type': 'gauge'},
{'metric': 'library.issue_count.count',
'points': [[1663348587.680466, 2.0]],
'tags': ['org:twilio',
'repo:twilio/twilio-node',
'category:question',
'type:helper'],
'type': 'gauge'},
{'metric': 'library.issue_count.count',
'points': [[1663348587.680543, 12.0]],
'tags': ['org:twilio',
'repo:twilio/twilio-node',
'category:bug',
'type:helper'],
'type': 'gauge'},
{'metric': 'library.issue_count.count',
'points': [[1663348587.680613, 3.0]],
'tags': ['org:twilio',
'repo:twilio/twilio-node', …
```

feat: add time_awaiting metric reporting to Datadog

---

examples/action_items.py
examples/common/issue.py
examples/common/labels.py

[Internal Ticket](https://issues.corp.twilio.com/browse/DI-2280)
Changes:
- Added new "Status: Waiting for feature" label to all repos in ALL_REPOS
- Modified action items to output all PRs tagged with "Status: Waiting for feature" to a new category, "PRs Waiting for feature"

feat: add "Status: Waiting for feature" label

---

actions/release/dist/index.js
examples/action_items.py
examples/common/issue.py
examples/common/labels.py

Fixes [Update-github-labels workflow failures
](https://github.com/sendgrid/dx-automator/actions/runs/4044638299)
-
-

fix: add stale and triage queue labels

---

examples/common/admins.py

chore: Added to tiwarishubham635 to admins
